### PR TITLE
Multiplayer patch

### PR DESCRIPTION
**Pull request by lassesjov**
Fixes default game walls not getting removed when joining a multiplayer session as a client.

Wall removal logic was moved to the moment of kitchen layout construction, which always runs on the client.
The logic for spawning custom wall entities remains in the NightSystem, which only runs on the host, but this is desired, as entities are already sent to clients.
<br>

Because the client doesn't check whether the host has the mod, clients will remove the walls regardless, possibly leaving a client wallless. (Optimal Solution WIP)

<br>

Debugging and game logic exploration done together with @MetaflameDragon

### CODE REVIEW

**Comment by Ashesh3** [comment]
This is really cool!, @Nitero did you find time to look at this? It'd be a nice addition.

**Comment by Nitero** [comment]
hey @lassesjov and sorry for the late reply, just fixed my notifications settings

the proper fix for multiplayer was supposed to be changing the layout directly, but I couldnt figure out how exactly
but this sounds good too, will take a look tomorrow and probably merge it

**Comment by lassesjov** [comment]
I see, no worries.

Changing the layout directly would definitely be ideal. Would also allow for the ability to make doors as some people have suggested/requested.

@MetaflameDragon how possible do you think that approach is?

**Comment by Nitero** [comment]
it should definitely be possible, I got some [help](https://discord.com/channels/1027159977040826408/1035906388284690453/1116193766102016062) from IcedMilo on discord and had a [test version](https://github.com/Nitero/Sledgehammer/compare/main...feature/hatch_via_layout_change) that replaced all walls via a layout refresh at night pretty well

the issue with this was that its not obvious what the values in the reachability matrix mean, but with a big radius it seems to produce a working hatch... the only remaining issue I couldnt solve is that the doors then wouldn't turn into hatches anymore when an appliance was put infront of them

if we could fix that I think it would just need a rework so that invisible entities trigger the layout change

**Comment by lassesjov** [comment]
Neat, that definitely sounds like something worth looking deeper into.
Great work!

**Comment by Nitero** [comment]
really sorry I forgot about this again, I dont have time to do the proper fix atm so I uploaded your solution, thanks for the work!

**Comment by lassesjov** [comment]
No worries, it'll work for now

**Pull request merged**
